// <auto-generated />
using System;
using ECommerce.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.WebAPI.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20250616210237_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ECommerce")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.WebAPI.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", "ECommerce");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electronic devices and gadgets",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computers and accessories",
                            IsActive = true,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Audio devices and accessories",
                            IsActive = true,
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming consoles and accessories",
                            IsActive = true,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothing and fashion accessories",
                            IsActive = true,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Home and garden products",
                            IsActive = true,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cameras and photography equipment",
                            IsActive = true,
                            Name = "Cameras"
                        });
                });

            modelBuilder.Entity("ECommerce.WebAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "ECommerce");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple iPhone 15 Pro 256GB Titanium Blue",
                            ImageUrl = "https://www.buseterim.com.tr/upload/default/2023/9/13/680.png",
                            IsActive = true,
                            Name = "iPhone 15 Pro",
                            Price = 45999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 1, 16, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Galaxy S24 Ultra 512GB Phantom Black",
                            ImageUrl = "https://images.samsung.com/is/image/samsung/assets/tr/smartphones/galaxy-s24-ultra/buy/01_S24Ultra-Group-KV_MO_0527_final.jpg?imbypass=true",
                            IsActive = true,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 42999.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 1, 17, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple MacBook Pro 14-inch M3 16GB RAM 512GB SSD",
                            ImageUrl = "https://www.notebookcheck-tr.com/fileadmin/_processed_/a/3/csm_IMG_1008_47c6b245b1.jpg",
                            IsActive = true,
                            Name = "MacBook Pro M3",
                            Price = 69999.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 18, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple AirPods Pro 2nd Generation with MagSafe Case",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MQD83",
                            IsActive = true,
                            Name = "AirPods Pro 2",
                            Price = 8999.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 1, 19, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony PlayStation 5 Console with DualSense Controller",
                            ImageUrl = "https://cdn03.ciceksepeti.com/cicek/kcm69709524-1/XL/sony-playstation-5-slim-cdli-2.-pembedualsense-oyun-konsolu-kcm69709524-1-ebf5b4b58f924c3596c35c40ce35c862.jpg",
                            IsActive = true,
                            Name = "Sony PlayStation 5",
                            Price = 18999.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 1, 20, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nike Air Max 270 Erkek Spor Ayakkabı - Siyah/Beyaz",
                            ImageUrl = "https://cdn03.ciceksepeti.com/cicek/kcm21428437-1/XL/nike-air-max-270-g.-s.-white-pink-sneaker-gunluk-spor-ayakkabi-beyaz-pembe-kcm21428437-2-5c72511cbf2e4a31bb3edee4d9f699cb.jpg",
                            IsActive = true,
                            Name = "Nike Air Max 270",
                            Price = 3499.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 1, 21, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung 55-inch QLED 4K Smart TV QE55Q70C",
                            ImageUrl = "https://images.samsung.com/is/image/samsung/p6pim/tr/qe55q60dauxtk/gallery/tr-qled-q60d-504767-qe55q60dauxtk-541172747?$684_547_PNG$",
                            IsActive = true,
                            Name = "Samsung 55\" QLED TV",
                            Price = 24999.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bose QuietComfort 45 Kablosuz Gürültü Önleyici Kulaklık",
                            ImageUrl = "https://static.ticimax.cloud/79/uploads/urunresimleri/buyuk/bose-quietcomfort-45-beyaz-gurultu-onl-2624-8.jpg",
                            IsActive = true,
                            Name = "Bose QuietComfort 45",
                            Price = 12999.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Levi's 501 Original Straight Fit Erkek Jean Pantolon",
                            ImageUrl = "https://lsco.scene7.com/is/image/lsco/005010114-front-pdp",
                            IsActive = true,
                            Name = "Levi's 501 Original Jeans",
                            Price = 1299.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 1, 24, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dyson V15 Detect Kablosuz Süpürge - Lazer Teknolojisi",
                            ImageUrl = "https://cdn.dsmcdn.com/ty1579/prod/QC/20241004/11/29ae1021-584f-3599-8dec-ddeccf7a0efc/1_org_zoom.jpg",
                            IsActive = true,
                            Name = "Dyson V15 Detect",
                            Price = 15999.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 1, 25, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Canon EOS R6 Mark II Aynasız Fotoğraf Makinesi Body",
                            ImageUrl = "https://i1.adis.ws/i/canon/09_frontback-pro_0c048afdc81c488eb9e5592f9cccc06e",
                            IsActive = true,
                            Name = "Canon EOS R6 Mark II",
                            Price = 89999.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 1, 26, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adidas Ultraboost 23 Erkek Koşu Ayakkabısı - Beyaz",
                            ImageUrl = "https://cdn.modalite.net/img/bf/2f/bf2fa929-2d11-aeac-6a5d-ecbc9e83ea55.jpg",
                            IsActive = true,
                            Name = "Adidas Ultraboost 23",
                            Price = 4999.99m,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("ECommerce.WebAPI.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.WebAPI.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.WebAPI.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
