// <auto-generated />
using System;
using ECommerce.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.WebAPI.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    partial class ECommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ECommerce")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.WebAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", "ECommerce");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple iPhone 15 Pro 256GB Titanium Blue",
                            ImageUrl = "https://example.com/images/iphone15pro.jpg",
                            IsActive = true,
                            Name = "iPhone 15 Pro",
                            Price = 45999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 1, 16, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Galaxy S24 Ultra 512GB Phantom Black",
                            ImageUrl = "https://example.com/images/galaxys24ultra.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 42999.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            CreatedDate = new DateTime(2024, 1, 17, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple MacBook Pro 14-inch M3 16GB RAM 512GB SSD",
                            ImageUrl = "https://example.com/images/macbookprom3.jpg",
                            IsActive = true,
                            Name = "MacBook Pro M3",
                            Price = 69999.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Category = "Audio",
                            CreatedDate = new DateTime(2024, 1, 18, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple AirPods Pro 2nd Generation with MagSafe Case",
                            ImageUrl = "https://example.com/images/airpodspro2.jpg",
                            IsActive = true,
                            Name = "AirPods Pro 2",
                            Price = 8999.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "Gaming",
                            CreatedDate = new DateTime(2024, 1, 19, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony PlayStation 5 Console with DualSense Controller",
                            ImageUrl = "https://example.com/images/ps5.jpg",
                            IsActive = true,
                            Name = "Sony PlayStation 5",
                            Price = 18999.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fashion",
                            CreatedDate = new DateTime(2024, 1, 20, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nike Air Max 270 Erkek Spor Ayakkabı - Siyah/Beyaz",
                            ImageUrl = "https://example.com/images/nikeairmax270.jpg",
                            IsActive = true,
                            Name = "Nike Air Max 270",
                            Price = 3499.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 1, 21, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung 55-inch QLED 4K Smart TV QE55Q70C",
                            ImageUrl = "https://example.com/images/samsungqledtv.jpg",
                            IsActive = true,
                            Name = "Samsung 55\" QLED TV",
                            Price = 24999.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            Category = "Audio",
                            CreatedDate = new DateTime(2024, 1, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bose QuietComfort 45 Kablosuz Gürültü Önleyici Kulaklık",
                            ImageUrl = "https://example.com/images/bosequietcomfort45.jpg",
                            IsActive = true,
                            Name = "Bose QuietComfort 45",
                            Price = 12999.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            Category = "Fashion",
                            CreatedDate = new DateTime(2024, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Levi's 501 Original Straight Fit Erkek Jean Pantolon",
                            ImageUrl = "https://example.com/images/levis501.jpg",
                            IsActive = true,
                            Name = "Levi's 501 Original Jeans",
                            Price = 1299.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 10,
                            Category = "Home & Garden",
                            CreatedDate = new DateTime(2024, 1, 24, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dyson V15 Detect Kablosuz Süpürge - Lazer Teknolojisi",
                            ImageUrl = "https://example.com/images/dysonv15.jpg",
                            IsActive = true,
                            Name = "Dyson V15 Detect",
                            Price = 15999.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 11,
                            Category = "Cameras",
                            CreatedDate = new DateTime(2024, 1, 25, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Canon EOS R6 Mark II Aynasız Fotoğraf Makinesi Body",
                            ImageUrl = "https://example.com/images/canoneosr6.jpg",
                            IsActive = true,
                            Name = "Canon EOS R6 Mark II",
                            Price = 89999.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 12,
                            Category = "Fashion",
                            CreatedDate = new DateTime(2024, 1, 26, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adidas Ultraboost 23 Erkek Koşu Ayakkabısı - Beyaz",
                            ImageUrl = "https://example.com/images/adidasultraboost.jpg",
                            IsActive = true,
                            Name = "Adidas Ultraboost 23",
                            Price = 4999.99m,
                            Stock = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
